[package]
name = "neuralnet"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.22.0"
env_logger = "0.11.7"
futures-intrusive = "0.5.0"
pollster = "0.4.0"
serde_json = "=1.0.140"
wgpu = "24.0.1"
